BEGIN;

CREATE TABLE IF NOT EXISTS 
  accounts_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc'))
  );

CREATE UNIQUE INDEX idx_accounts_types_name_idx ON accounts_types(name);

COMMIT;