BEGIN;

CREATE TABLE IF NOT EXISTS 
  authorization_status (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc'))
  );

CREATE UNIQUE INDEX idx_authorization_status_name_idx ON authorization_status(name);

COMMIT;