BEGIN;

CREATE TABLE IF NOT EXISTS
  accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address text NOT NULL,
    account_type integer NOT NULL REFERENCES accounts_types (id),
    created_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc'))
  );

CREATE UNIQUE INDEX accounts_idx ON accounts (wallet_address);

CREATE INDEX accounts_types_idx ON accounts (account_type);

COMMIT;